import express from "express";
import authRoutes from "./authRoutes.js";
import organizationRoutes from "./organizationRoutes.js";
import membershipRoutes from "./membershipRoutes.js";
import membershipRequestRoutes from "./membershipRequestRoutes.js";
import invitationRoutes from "./invitationRoutes.js";
import meetingRoutes from "./meetingRoutes.js";
import searchRoutes from "./searchRoutes.js";
import aiRoutes from "./aiRoutes.js";
import policyRoutes from "./policyRoutes.js";
import analyticsRoutes from "./analyticsRoutes.js";
import geminiRoutes from "./geminiRoutes.js";
import userRoutes from "./userRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import knowledgeRoutes from "./knowledgeRoutes.js";
import policyComplianceRoutes from "./policyComplianceRoutes.js";
import sessionRoutes from "./sessionRoutes.js";
import transcriptRoutes from "./transcriptRoutes.js";
import sharedLinkRoutes from "./sharedLinkRoutes.js";
import meetingTemplateRoutes from "./meetingTemplateRoutes.js";
import bookmarkRoutes from "./bookmarkRoutes.js";
import commentRoutes from "./commentRoutes.js";
import activityRoutes from "./activityRoutes.js";
import tagRoutes from "./tagRoutes.js";
import pollRoutes from "./pollRoutes.js";
import attachmentRoutes from "./attachmentRoutes.js";
import meetingSeriesRoutes from "./meetingSeriesRoutes.js";
import comparisonRoutes from "./comparisonRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";
import agendaTimerRoutes from "./agendaTimerRoutes.js";
import digestRoutes from "./digestRoutes.js";
import decisionGraphRoutes from "./decisionGraphRoutes.js";
import attendanceAnalyticsRoutes from "./attendanceAnalyticsRoutes.js";
import meetingFeedbackRoutes from "./meetingFeedbackRoutes.js";
import meetingCostRoutes from "./meetingCostRoutes.js";
import followUpThreadRoutes from "./followUpThreadRoutes.js";
import recapScheduleRoutes from "./recapScheduleRoutes.js";
import meetingClipRoutes from "./meetingClipRoutes.js";
import speakerMappingRoutes from "./speakerMappingRoutes.js";
import noteVersionRoutes from "./noteVersionRoutes.js";
import reportRoutes from "./reportRoutes.js";
import agendaSuggestionRoutes from "./agendaSuggestionRoutes.js";
import translationRoutes from "./translationRoutes.js";
import personalNoteRoutes from "./personalNoteRoutes.js";
import templateLibraryRoutes from "./templateLibraryRoutes.js";
import transcriptAnnotationRoutes from "./transcriptAnnotationRoutes.js";
import glossaryRoutes from "./glossaryRoutes.js";
import aiSummaryTemplateRoutes from "./aiSummaryTemplateRoutes.js";
import topicRoutes from "./topicRoutes.js";

const router = express.Router();

// ==========================================
// ALL PROTECTED ROUTES (CSRF Enforced globally in express.js)
// ==========================================
router.use("/api/auth", authRoutes);
router.use(["/api/organization", "/api/organizations"], organizationRoutes);
router.use("/api/membership", membershipRoutes);
router.use("/api/membership-request", membershipRequestRoutes);
router.use("/api/invitation", invitationRoutes);
router.use("/api/meetings/timer", agendaTimerRoutes);
router.use("/api/meetings", meetingRoutes);
router.use("/api/search", searchRoutes);
router.use("/api/ai", aiRoutes);
router.use("/api/policies", policyRoutes);
router.use("/api/analytics", analyticsRoutes);
router.use("/api/gemini", geminiRoutes);
router.use("/api/user", userRoutes);
router.use("/api/notifications", notificationRoutes);
router.use("/api/knowledge", knowledgeRoutes);
router.use("/api/compliance", policyComplianceRoutes);
router.use("/api/sessions", sessionRoutes);
router.use("/api/transcripts", transcriptRoutes);
router.use("/api/shared-links", sharedLinkRoutes);
router.use("/api/templates", meetingTemplateRoutes);
router.use("/api/bookmarks", bookmarkRoutes);
router.use("/api/comments", commentRoutes);
router.use("/api/activities", activityRoutes);
router.use("/api/tags", tagRoutes);
router.use("/api/polls", pollRoutes);
router.use("/api/meetings/:meetingId/attachments", attachmentRoutes);
router.use("/api/meeting-series", meetingSeriesRoutes);
router.use("/api/comparison", comparisonRoutes);
router.use("/api/dashboard", dashboardRoutes);
router.use("/api/digest-preferences", digestRoutes);
router.use("/api/decision-graph", decisionGraphRoutes);
router.use("/api/attendance-analytics", attendanceAnalyticsRoutes);
router.use("/api/feedback", meetingFeedbackRoutes);
router.use("/api/meeting-cost", meetingCostRoutes);
router.use("/api/follow-up-threads", followUpThreadRoutes);
router.use("/api/recap-schedule", recapScheduleRoutes);
router.use("/api/clips", meetingClipRoutes);
router.use("/api/speaker-mappings", speakerMappingRoutes);
router.use("/api/note-versions", noteVersionRoutes);
router.use("/api/reports", reportRoutes);
router.use("/api/agenda-suggestions", agendaSuggestionRoutes);
router.use("/api/translations", translationRoutes);
router.use("/api/personal-notes", personalNoteRoutes);
router.use("/api/template-library", templateLibraryRoutes);
router.use("/api/transcript-annotations", transcriptAnnotationRoutes);
router.use("/api/glossary", glossaryRoutes);
router.use("/api/ai-summary-templates", aiSummaryTemplateRoutes);
router.use("/api/topics", topicRoutes);

export default router;
