export const mapActionItemsToGithubIssue = (meeting, actionItems) => {
  if (!actionItems || actionItems.length === 0) return null;

  const issueTitle = `[Action Items] ${meeting.title} - ${new Date(meeting.date).toDateString()}`;
  
  let issueBody = `## Meeting Action Items\n\n`;
  issueBody += `**Meeting:** ${meeting.title}\n**Date:** ${new Date(meeting.date).toDateString()}\n\n`;
  
  issueBody += `### Tasks\n`;
  actionItems.forEach((item, index) => {
    issueBody += `- [ ] **Task ${index + 1}:** ${item}\n`;
  });
  
  issueBody += `\n\n*Generated by MeetOnMemory AI Synchronization*`;
  
  return {
    title: issueTitle,
    body: issueBody,
    labels: ["meeting-action-items", "auto-generated"]
  };
};
