import { Octokit } from "@octokit/rest";
import GithubIntegration from "../models/githubIntegrationModel.js";
import GitHubIssueSync from "../models/githubIssueSyncModel.js";
import ActionItem from "../models/actionItemModel.js";
import { decryptToken } from "../utils/crypto.js";
import logger from "../utils/logger.js";

/**
 * Resolve the organization ID for an action item, falling back to its meeting.
 */
async function resolveOrganizationId(actionItem) {
  if (actionItem.organization) return actionItem.organization;

  const meetingId = actionItem.sourceMeetingId || actionItem.meetingId;
  if (!meetingId) return null;

  const Meeting = (await import("../models/meetingModel.js")).default;
  const meeting = await Meeting.findById(meetingId)
    .select("organizationId")
    .lean();
  return meeting?.organizationId ?? null;
}

/**
 * Build an authenticated Octokit instance for an organization.
 * Returns { octokit, integration } or null if no integration exists.
 */
export async function getOctokitForOrg(orgId) {
  const integration = await GithubIntegration.findOne({ organization: orgId });
  if (!integration?.accessToken) return null;

  const token = decryptToken(integration.accessToken);
  return {
    octokit: new Octokit({ auth: token }),
    integration,
  };
}

/**
 * Push an ActionItem to GitHub Issues (Issue #1600).
 *
 * Idempotent: if a sync mapping already exists for this action item + repo,
 * the existing GitHub Issue is returned without creating a duplicate.
 */
export const syncActionItemToGitHub = async (actionItem) => {
  const orgId = await resolveOrganizationId(actionItem);
  if (!orgId) return null;

  const ctx = await getOctokitForOrg(orgId);
  if (!ctx) return null;

  const { octokit, integration } = ctx;
  const [owner, repo] = integration.repositoryFullName.split("/");

  const existingSync = await GitHubIssueSync.findOne({
    organization: orgId,
    actionItem: actionItem._id,
    repositoryFullName: integration.repositoryFullName,
  });

  if (existingSync) {
    logger.info(
      `ActionItem ${actionItem._id} already synced to GitHub Issue #${existingSync.githubIssueNumber}`,
    );
    return {
      number: existingSync.githubIssueNumber,
      html_url: existingSync.githubIssueUrl,
      alreadySynced: true,
    };
  }

  const title =
    actionItem.text.length > 80
      ? actionItem.text.substring(0, 77) + "..."
      : actionItem.text;

  const frontendUrl = process.env.CLIENT_URL || "http://localhost:3000";
  const meetingLink = `${frontendUrl}/meeting/${actionItem.sourceMeetingId}`;

  let body = `**Action Item generated by MeetOnMemory**\n\n`;
  body += `**Description:** ${actionItem.text}\n\n`;
  body += `**Source Meeting:** [View Meeting](${meetingLink})\n\n`;

  if (actionItem.owner && actionItem.owner !== "Unassigned") {
    body += `**Assigned to:** ${actionItem.owner}\n`;
  }

  const response = await octokit.rest.issues.create({
    owner,
    repo,
    title,
    body,
  });

  const ghIssue = response.data;

  actionItem.externalGitHubIssueId = ghIssue.number;
  actionItem.externalGitHubIssueUrl = ghIssue.html_url;
  await actionItem.save();

  await GitHubIssueSync.create({
    organization: orgId,
    actionItem: actionItem._id,
    meetingId: actionItem.sourceMeetingId || null,
    repositoryFullName: integration.repositoryFullName,
    githubIssueNumber: ghIssue.number,
    githubIssueNodeId: ghIssue.node_id || null,
    githubIssueUrl: ghIssue.html_url,
    lastSyncDirection: "push",
    lastSyncedAt: new Date(),
  });

  logger.info(
    `ActionItem ${actionItem._id} synced → GitHub Issue #${ghIssue.number}`,
  );

  return ghIssue;
};

/**
 * Handle a GitHub issue event received via webhook (Issue #1600).
 *
 * Looks up the ActionItem through the sync mapping (scoped by repo + issue number)
 * to avoid cross-repo collisions.
 */
export async function handleGitHubIssueEvent({ action, issue, repository }) {
  const repoFullName = repository?.full_name;
  if (!repoFullName || !issue?.number) return { updated: false };

  const syncMapping = await GitHubIssueSync.findOne({
    repositoryFullName: repoFullName,
    githubIssueNumber: issue.number,
  });

  if (!syncMapping) {
    return { updated: false, reason: "no_mapping" };
  }

  const actionItem = await ActionItem.findById(syncMapping.actionItem);
  if (!actionItem) {
    return { updated: false, reason: "action_item_not_found" };
  }

  let newStatus = null;
  if (action === "closed") {
    newStatus = "completed";
  } else if (action === "reopened") {
    newStatus = "open";
  }

  if (!newStatus || actionItem.status === newStatus) {
    return { updated: false, reason: "no_status_change" };
  }

  actionItem.status = newStatus;
  if (newStatus === "completed") {
    actionItem.resolvedAt = new Date();
    actionItem.completedAt = new Date();
  } else {
    actionItem.resolvedAt = null;
    actionItem.completedAt = null;
  }
  await actionItem.save();

  syncMapping.lastSyncDirection = "webhook";
  syncMapping.lastSyncedAt = new Date();
  await syncMapping.save();

  logger.info(
    `ActionItem ${actionItem._id} status → "${newStatus}" via GitHub webhook (${repoFullName}#${issue.number})`,
  );

  return { updated: true, actionItemId: actionItem._id.toString(), newStatus };
}
