import axios from "axios";
import IssueTrackerIntegration from "../models/issueTrackerIntegrationModel.js";

/**
 * Push a new Action Item to Jira
 */
export const syncActionItemToJira = async (actionItem) => {
  try {
    let orgId = actionItem.organization;

    if (!orgId) {
      const Meeting = (await import("../models/meetingModel.js")).default;
      const meetingId = actionItem.sourceMeetingId || actionItem.meetingId;
      if (!meetingId) return;

      const meeting = await Meeting.findById(meetingId);
      if (!meeting || !meeting.organizationId) return;
      orgId = meeting.organizationId;
    }

    if (!orgId) return;

    const integration = await IssueTrackerIntegration.findOne({
      organization: orgId,
      provider: "jira",
    });

    if (!integration) {
      return; // No integration found, do nothing
    }

    const { accessToken, config } = integration;
    if (!config || !config.projectKey) {
      return; // Not configured properly
    }

    // Assuming we use Jira Cloud REST API v3
    // E.g., domain usually comes from config if OAuth, or it's a fixed tenant
    // We'll assume cloudId or siteUrl is stored in config
    const siteUrl = config.siteUrl;
    if (!siteUrl) return;

    const title =
      actionItem.text.length > 80
        ? actionItem.text.substring(0, 77) + "..."
        : actionItem.text;

    const frontendUrl = process.env.CLIENT_URL || "http://localhost:3000";
    const meetingLink = `${frontendUrl}/meeting/${actionItem.sourceMeetingId}`;

    let description = `*Action Item generated by MeetOnMemory*\n\n`;
    description += `*Description:* ${actionItem.text}\n\n`;
    description += `*Source Meeting:* [View Meeting|${meetingLink}]\n\n`;

    if (actionItem.owner && actionItem.owner !== "Unassigned") {
      description += `*Assigned to:* ${actionItem.owner}\n`;
    }

    const payload = {
      fields: {
        project: {
          key: config.projectKey,
        },
        summary: title,
        description: {
          type: "doc",
          version: 1,
          content: [
            {
              type: "paragraph",
              content: [
                {
                  type: "text",
                  text: description,
                },
              ],
            },
          ],
        },
        issuetype: {
          name: "Task", // Default to Task
        },
      },
    };

    const response = await axios.post(`${siteUrl}/rest/api/3/issue`, payload, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
    });

    // Update ActionItem with Jira data
    actionItem.externalJiraIssueId = response.data.key;
    actionItem.externalJiraIssueUrl = `${siteUrl}/browse/${response.data.key}`;
    await actionItem.save();

    // Update integration sync status metrics
    integration.lastSyncAt = new Date();
    integration.lastSyncStatus = "success";
    integration.lastSyncError = null;
    integration.syncCount = (integration.syncCount || 0) + 1;
    integration.syncLogs = [
      {
        timestamp: new Date(),
        action: "outbound_push",
        status: "success",
        details: `Created Jira issue ${response.data.key}`,
      },
      ...(integration.syncLogs || []),
    ].slice(0, 15);
    await integration.save();

    return response.data;
  } catch (error) {
    console.error(
      "Error syncing Action Item to Jira:",
      error?.response?.data || error,
    );
    throw error;
  }
};
